<?php

namespace ContainerUADXgRp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserBalanceControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\UserBalanceController' shared autowired service.
     *
     * @return \App\Controller\UserBalanceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/UserBalanceController.php';

        $container->services['App\\Controller\\UserBalanceController'] = $instance = new \App\Controller\UserBalanceController(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\UserBalanceController', $container));

        return $instance;
    }
}
