<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKWlit08\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKWlit08/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKWlit08.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKWlit08\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKWlit08\App_KernelDevDebugContainer([
    'container.build_hash' => 'KWlit08',
    'container.build_id' => 'e778385f',
    'container.build_time' => 1657008671,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKWlit08');
