<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLGa8pxa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLGa8pxa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLGa8pxa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLGa8pxa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLGa8pxa\App_KernelDevDebugContainer([
    'container.build_hash' => 'LGa8pxa',
    'container.build_id' => '5fe0a137',
    'container.build_time' => 1656989531,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLGa8pxa');
