<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCQMsFZw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCQMsFZw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCQMsFZw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCQMsFZw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCQMsFZw\App_KernelDevDebugContainer([
    'container.build_hash' => 'CQMsFZw',
    'container.build_id' => 'cc3b675b',
    'container.build_time' => 1656987803,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCQMsFZw');
