<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LogoutController::index'], [], [['text', '/logout']], [], [], []],
    'products_list' => [[], ['_controller' => 'App\\Controller\\ProductController::indexAction'], [], [['text', '/api/products']], [], [], []],
    'create_product' => [[], ['_controller' => 'App\\Controller\\ProductController::createAction'], [], [['text', '/api/products']], [], [], []],
    'delete_product' => [['id'], ['_controller' => 'App\\Controller\\ProductController::deleteAction'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/product']], [], [], []],
    'app_registration' => [[], ['_controller' => 'App\\Controller\\RegistrationController::index'], [], [['text', '/registration']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
