<?php

namespace ContainerLGa8pxa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCanteenControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CanteenController' shared autowired service.
     *
     * @return \App\Controller\CanteenController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CanteenController.php';

        $container->services['App\\Controller\\CanteenController'] = $instance = new \App\Controller\CanteenController(($container->privates['App\\Repository\\CanteenRepository'] ?? $container->load('getCanteenRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\CanteenController', $container));

        return $instance;
    }
}
